#gcc -Wall -Werror -Wextra -Wpedantic -I. -I../include -o nsga2r allocate.c auxiliary.c crossover.c crowddist.c decode.c display.c dominance.c eval.c fillnds.c initialize.c list.c merge.c mutation.c nsga2.c nsga2r.c problemdef.c rand.c rank.c report.c sort.c tourselect.c snnfuncs.c distance_comp.c ../src/snn_library.c ../src/load_data.c ../src/helpers.c ../src/neuron_models/lif_neuron.c ../src/training_rules/stdp.c ../src/simulations/simulations.c motifs.c ../src/encoders/image_encoders.c -lm

gcc -Wall -Wextra -Wpedantic -I. -I../include -o nsga2r allocate.c auxiliary.c crossover.c crowddist.c decode.c display.c dominance.c eval.c fillnds.c initialize.c list.c merge.c mutation.c nsga2.c nsga2r.c problemdef.c rand.c rank.c report.c sort.c tourselect.c snnfuncs.c distance_comp.c ../src/snn_library.c ../src/load_data.c ../src/helpers.c ../src/neuron_models/lif_neuron.c ../src/training_rules/stdp.c ../src/simulations/simulations.c motifs.c ../src/encoders/image_encoders.c -lm
gcc -I. -I../include -o nsga2r_d1 allocate.c auxiliary.c crossover.c crowddist.c decode.c display.c dominance.c eval.c fillnds.c initialize.c list.c merge.c mutation.c nsga2.c nsga2r.c problemdef.c rand.c rank.c report.c sort.c tourselect.c snnfuncs.c distance_comp.c ../src/snn_library.c ../src/load_data.c ../src/helpers.c ../src/neuron_models/lif_neuron.c ../src/training_rules/stdp.c ../src/simulations/simulations.c motifs.c ../src/encoders/image_encoders.c -DDEBUG1 -lm
gcc -I. -I../include -o nsga2r_parallel allocate.c auxiliary.c crossover.c crowddist.c decode.c display.c dominance.c eval.c fillnds.c initialize.c list.c merge.c mutation.c nsga2.c nsga2r.c problemdef.c rand.c rank.c report.c sort.c tourselect.c snnfuncs.c distance_comp.c ../src/snn_library.c ../src/load_data.c ../src/helpers.c ../src/neuron_models/lif_neuron.c ../src/training_rules/stdp.c ../src/simulations/simulations.c motifs.c ../src/encoders/image_encoders.c -DOPENMP -fopenmp  -lm
gcc -g -O0 -I. -I../include -o nsga2r_debug allocate.c auxiliary.c crossover.c crowddist.c decode.c display.c dominance.c eval.c fillnds.c initialize.c list.c merge.c mutation.c nsga2.c nsga2r.c problemdef.c rand.c rank.c report.c sort.c tourselect.c snnfuncs.c distance_comp.c ../src/snn_library.c ../src/load_data.c ../src/helpers.c ../src/neuron_models/lif_neuron.c ../src/training_rules/stdp.c ../src/simulations/simulations.c motifs.c ../src/encoders/image_encoders.c -lm

#gcc -I. -I../include -o nsga2r_d1 allocate.c auxiliary.c crossover.c crowddist.c decode.c display.c dominance.c eval.c fillnds.c initialize.c list.c merge.c mutation.c nsga2.c nsga2r.c problemdef.c rand.c rank.c report.c sort.c tourselect.c snnfuncs.c distance_comp.c ../src/snn_library.c ../src/load_data.c ../src/helpers.c ../src/neuron_models/lif_neuron.c ../src/training_rules/stdp.c ../src/simulations/simulations.c motifs.c ../src/encoders/image_encoders.c -DDEBUG1 -lm
#gcc -I. -I../include -o nsga2r_d2 allocate.c auxiliary.c crossover.c crowddist.c decode.c display.c dominance.c eval.c fillnds.c initialize.c list.c merge.c mutation.c nsga2.c nsga2r.c problemdef.c rand.c rank.c report.c sort.c tourselect.c snnfuncs.c distance_comp.c ../src/snn_library.c ../src/load_data.c ../src/helpers.c ../src/neuron_models/lif_neuron.c ../src/training_rules/stdp.c ../src/simulations/simulations.c motifs.c ../src/encoders/image_encoders.c -DDEBUG1 -DDEBUG2 -lm
#gcc -I. -I../include -o nsga2r_d3 allocate.c auxiliary.c crossover.c crowddist.c decode.c display.c dominance.c eval.c fillnds.c initialize.c list.c merge.c mutation.c nsga2.c nsga2r.c problemdef.c rand.c rank.c report.c sort.c tourselect.c snnfuncs.c distance_comp.c ../src/snn_library.c ../src/load_data.c ../src/helpers.c ../src/neuron_models/lif_neuron.c ../src/training_rules/stdp.c ../src/simulations/simulations.c motifs.c ../src/encoders/image_encoders.c -DDEBUG1 -DDEBUG2 -DDEBUG3 -lm

#gcc -I. -I../include -o nsga2r_parallel_d1 allocate.c auxiliary.c crossover.c crowddist.c decode.c display.c dominance.c eval.c fillnds.c initialize.c list.c merge.c mutation.c nsga2.c nsga2r.c problemdef.c rand.c rank.c report.c sort.c tourselect.c snnfuncs.c distance_comp.c ../src/snn_library.c ../src/load_data.c ../src/helpers.c ../src/neuron_models/lif_neuron.c ../src/training_rules/stdp.c ../src/simulations/simulations.c motifs.c ../src/encoders/image_encoders.c -DOPENMP -DDEBUG1 -fopenmp  -lm
#gcc -I. -I../include -o nsga2r_parallel_d2 allocate.c auxiliary.c crossover.c crowddist.c decode.c display.c dominance.c eval.c fillnds.c initialize.c list.c merge.c mutation.c nsga2.c nsga2r.c problemdef.c rand.c rank.c report.c sort.c tourselect.c snnfuncs.c distance_comp.c ../src/snn_library.c ../src/load_data.c ../src/helpers.c ../src/neuron_models/lif_neuron.c ../src/training_rules/stdp.c ../src/simulations/simulations.c motifs.c ../src/encoders/image_encoders.c -DOPENMP -DDEBUG1 -DDEBUG2 -fopenmp  -lm
#gcc -I. -I../include -o nsga2r_parallel_d3 allocate.c auxiliary.c crossover.c crowddist.c decode.c display.c dominance.c eval.c fillnds.c initialize.c list.c merge.c mutation.c nsga2.c nsga2r.c problemdef.c rand.c rank.c report.c sort.c tourselect.c snnfuncs.c distance_comp.c ../src/snn_library.c ../src/load_data.c ../src/helpers.c ../src/neuron_models/lif_neuron.c ../src/training_rules/stdp.c ../src/simulations/simulations.c motifs.c ../src/encoders/image_encoders.c -DOPENMP -DDEBUG1 -DDEBUG2  -DDEBUG3 -fopenmp  -lm
